// src/renderer/src/screens/GhostChat.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import GhostMascot from '../components/GhostMascot.svelte';
  import { onGhostMessage, onChatResponse, sendChat } from '../lib/electron';
  import { chatHistory, isThinking } from '../stores/app';
  import type { ChatEntry, GhostMessagePayload, ChatResponsePayload } from '@shared/ipc-contract';
  import GhostBubble from '../components/GhostBubble.svelte';
  import UserBubble from '../components/UserBubble.svelte';
  import ThinkingBubble from '../components/ThinkingBubble.svelte';

  interface Props {
    onBack: () => void;
  }

  let { onBack }: Props = $props();

  // Initialize from store to get real data immediately on mount
  let messages = $state<ChatEntry[]>([...$chatHistory]);
  let input = $state('');
  let thinking = $state($isThinking);
  let scrollRef: HTMLDivElement | null = $state(null);

  // Keep in sync with store
  chatHistory.subscribe(h => messages = h);
  isThinking.subscribe(t => thinking = t);

  function handleSend() {
    const text = input.trim();
    if (!text || thinking) return;
    input = '';
    const entry: ChatEntry = { role: 'user', content: text, timestamp: Date.now() };
    const next = [...messages, entry];
    messages = next;
    chatHistory.set(next);
    thinking = true;
    isThinking.set(true);
    sendChat(text, next);
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') handleSend();
  }

  onMount(() => {
    onGhostMessage((d: GhostMessagePayload) => {
      messages = [...messages, { role: 'ghost', content: d.message, timestamp: d.timestamp }];
      chatHistory.set(messages);
    });
    onChatResponse((d: ChatResponsePayload) => {
      thinking = false;
      isThinking.set(false);
      messages = [...messages, { role: 'ghost', content: d.message, timestamp: d.timestamp }];
      chatHistory.set(messages);
    });
  });

  $effect(() => {
    if (scrollRef && messages) {
      scrollRef.scrollTop = scrollRef.scrollHeight;
    }
  });
</script>

<div class="chat-container">
  <div class="chat-header">
    <button class="back-btn" onclick={onBack} aria-label="back">
      ←
    </button>
    <GhostMascot state="calm" size={30} />
    <div class="chat-title">
      <div class="title-main">ghost companion</div>
      <div class="title-sub">your focus buddy</div>
    </div>
    <div class="live-indicator">
      <div class="live-dot"></div>
      live
    </div>
  </div>

  <div class="message-list fg-scroll" bind:this={scrollRef}>
    {#each messages as msg}
      {#if msg.role === 'user'}
        <UserBubble entry={msg} />
      {:else}
        <GhostBubble entry={msg} />
      {/if}
    {/each}
    {#if thinking}
      <ThinkingBubble />
    {/if}
  </div>

  <div class="composer">
    <div class="composer-inner">
      <input
        type="text"
        bind:value={input}
        onkeydown={handleKeyDown}
        placeholder="chat with your ghost…"
        class="composer-input"
      />
      <button
        class="send-btn"
        class:enabled={input.trim() && !thinking}
        disabled={!input.trim() || thinking}
        aria-label="send"
        onclick={handleSend}
      >
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
          <path
            d="M1.5 6L10.5 1.5L8 6L10.5 10.5L1.5 6Z"
            stroke={input.trim() && !thinking ? '#0a0a0a' : '#2dd4bf'}
            stroke-width="1"
            stroke-linejoin="round"
            fill={input.trim() && !thinking ? '#0a0a0a' : 'none'}
          />
        </svg>
      </button>
    </div>
  </div>
</div>

<style>
  .chat-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    font-family: 'Inter', sans-serif;
    color: #e5e5e5;
    overflow: hidden;
  }
  .chat-header {
    padding: 12px 14px;
    border-bottom: 0.5px solid rgba(255,255,255,0.06);
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .back-btn {
    background: transparent;
    border: none;
    color: #737373;
    font-size: 14;
    cursor: pointer;
    padding: 0;
    line-height: 1;
    flex-shrink: 0;
  }
  .chat-title {
    flex: 1;
    min-width: 0;
  }
  .title-main {
    font-size: 12px;
    font-weight: 500;
    color: #e5e5e5;
    letter-spacing: -0.01em;
  }
  .title-sub {
    font-size: 10px;
    color: #737373;
  }
  .live-indicator {
    display: flex;
    align-items: center;
    gap: 5px;
    font-size: 9px;
    color: #2dd4bf;
    letter-spacing: 0.06em;
    text-transform: uppercase;
  }
  .live-dot {
    width: 5px;
    height: 5px;
    border-radius: 50%;
    background: #2dd4bf;
    animation: pulseDot 2s ease-in-out infinite;
  }
  .message-list {
    flex: 1;
    overflow-y: auto;
    padding: 14px 12px;
    display: flex;
    flex-direction: column;
    gap: 12px;
  }
  .composer {
    padding: 10px 12px 12px;
    border-top: 0.5px solid rgba(255,255,255,0.06);
  }
  .composer-inner {
    display: flex;
    align-items: center;
    gap: 8px;
    background: #1a1a1a;
    border: 0.5px solid rgba(255,255,255,0.08);
    border-radius: 18px;
    padding: 4px 4px 4px 12px;
  }
  .composer-input {
    flex: 1;
    background: transparent;
    border: none;
    outline: none;
    font-size: 11px;
    color: #e5e5e5;
    font-family: inherit;
    padding: 6px 0;
  }
  .composer-input::placeholder {
    color: #525252;
  }
  .send-btn {
    width: 26px;
    height: 26px;
    border-radius: 50%;
    background: rgba(45,212,191,0.15);
    border: none;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: default;
    transition: all 0.15s;
    flex-shrink: 0;
  }
  .send-btn.enabled {
    background: #2dd4bf;
    cursor: pointer;
  }
</style>

// src/renderer/screens/GhostChat.tsx
import React, { useEffect, useRef, useState } from "react";
import GhostMascot from "../components/GhostMascot";
import type {
  ChatEntry,
  GhostMessagePayload,
  ChatResponsePayload,
} from "../../shared/ipc-contract";
import { IPC } from "../../shared/ipc-contract";

interface Props {
  onBack: () => void;
}

function relativeTime(timestamp: number): string {
  const sec = Math.floor((Date.now() - timestamp) / 1000);
  if (sec < 60) return "just now";
  const m = Math.floor(sec / 60);
  if (m < 60) return `${m}m ago`;
  return `${Math.floor(m / 60)}h ago`;
}

export default function GhostChat({ onBack }: Props) {
  const [chatHistory, setChatHistory] = useState<ChatEntry[]>([]);
  const [input, setInput] = useState("");
  const [isThinking, setIsThinking] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    window.electronAPI.onGhostMessage((d) => {
      const m = d as GhostMessagePayload;
      setChatHistory((h) => [
        ...h,
        { role: "ghost", content: m.message, timestamp: m.timestamp },
      ]);
    });
    window.electronAPI.onChatResponse((d) => {
      const r = d as ChatResponsePayload;
      setIsThinking(false);
      setChatHistory((h) => [
        ...h,
        { role: "ghost", content: r.message, timestamp: r.timestamp },
      ]);
    });

    return () => {
      window.electronAPI.removeAllListeners(IPC.GHOST_MESSAGE);
      window.electronAPI.removeAllListeners(IPC.CHAT_RESPONSE);
    };
  }, []);

  // Auto-scroll on new messages
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [chatHistory, isThinking]);

  const sendMessage = () => {
    const text = input.trim();
    if (!text || isThinking) return;
    setInput("");
    const entry: ChatEntry = {
      role: "user",
      content: text,
      timestamp: Date.now(),
    };
    const next = [...chatHistory, entry];
    setChatHistory(next);
    setIsThinking(true);
    window.electronAPI.sendChat({ message: text, chatHistory: next });
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") sendMessage();
  };

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        height: "100%",
        fontFamily: "'Inter', sans-serif",
        color: "#e5e5e5",
        overflow: "hidden",
      }}
    >
      {/* Header */}
      <div
        style={{
          padding: "12px 14px",
          borderBottom: "0.5px solid rgba(255,255,255,0.06)",
          display: "flex",
          alignItems: "center",
          gap: 10,
        }}
      >
        <button
          onClick={onBack}
          aria-label="back"
          style={{
            background: "transparent",
            border: "none",
            color: "#737373",
            fontSize: 14,
            cursor: "pointer",
            padding: 0,
            lineHeight: 1,
            flexShrink: 0,
          }}
        >
          ←
        </button>
        <GhostMascot state="calm" size={30} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div
            style={{
              fontSize: 12,
              fontWeight: 500,
              color: "#e5e5e5",
              letterSpacing: "-0.01em",
            }}
          >
            ghost companion
          </div>
          <div style={{ fontSize: 10, color: "#737373" }}>your focus buddy</div>
        </div>
        {/* Live indicator */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 5,
            fontSize: 9,
            color: "#2dd4bf",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
          }}
        >
          <div
            style={{
              width: 5,
              height: 5,
              borderRadius: "50%",
              background: "#2dd4bf",
              animation: "pulseDot 2s ease-in-out infinite",
            }}
          />
          live
        </div>
      </div>

      {/* Message list */}
      <div
        ref={scrollRef}
        className="fg-scroll"
        style={{
          flex: 1,
          overflowY: "auto",
          padding: "14px 12px",
          display: "flex",
          flexDirection: "column",
          gap: 12,
        }}
      >
        {chatHistory.map((msg, i) =>
          msg.role === "user" ? (
            <UserBubble key={i} entry={msg} />
          ) : (
            <GhostBubble key={i} entry={msg} />
          ),
        )}
        {isThinking && <ThinkingBubble />}
      </div>

      {/* Composer */}
      <div
        style={{
          padding: "10px 12px 12px",
          borderTop: "0.5px solid rgba(255,255,255,0.06)",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            background: "#1a1a1a",
            border: "0.5px solid rgba(255,255,255,0.08)",
            borderRadius: 18,
            padding: "4px 4px 4px 12px",
          }}
        >
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="chat with your ghost…"
            style={{
              flex: 1,
              background: "transparent",
              border: "none",
              outline: "none",
              fontSize: 11,
              color: "#e5e5e5",
              fontFamily: "inherit",
              padding: "6px 0",
            }}
          />
          <button
            onClick={sendMessage}
            disabled={!input.trim() || isThinking}
            aria-label="send"
            style={{
              width: 26,
              height: 26,
              borderRadius: "50%",
              background:
                input.trim() && !isThinking
                  ? "#2dd4bf"
                  : "rgba(45,212,191,0.15)",
              border: "none",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              cursor: input.trim() && !isThinking ? "pointer" : "default",
              transition: "all 0.15s",
              flexShrink: 0,
            }}
          >
            <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
              <path
                d="M1.5 6L10.5 1.5L8 6L10.5 10.5L1.5 6Z"
                stroke={input.trim() && !isThinking ? "#0a0a0a" : "#2dd4bf"}
                strokeWidth="1"
                strokeLinejoin="round"
                fill={input.trim() && !isThinking ? "#0a0a0a" : "none"}
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
}

function GhostBubble({ entry }: { entry: ChatEntry }) {
  return (
    <div
      style={{
        display: "flex",
        gap: 8,
        alignItems: "flex-start",
        paddingRight: 20,
      }}
    >
      <div style={{ flexShrink: 0, marginTop: 2 }}>
        <GhostMascot state="calm" size={22} />
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div
          style={{
            background: "#1a1a1a",
            border: "0.5px solid rgba(255,255,255,0.06)",
            borderRadius: "2px 10px 10px 10px",
            padding: "7px 10px",
            fontSize: 11,
            color: "#d4d4d4",
            lineHeight: 1.5,
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
          }}
        >
          {entry.content}
        </div>
        <div
          style={{
            fontSize: 9,
            color: "#525252",
            marginTop: 3,
            paddingLeft: 2,
          }}
        >
          {relativeTime(entry.timestamp)}
        </div>
      </div>
    </div>
  );
}

function UserBubble({ entry }: { entry: ChatEntry }) {
  return (
    <div
      style={{ display: "flex", justifyContent: "flex-end", paddingLeft: 32 }}
    >
      <div>
        <div
          style={{
            background: "rgba(45,212,191,0.12)",
            border: "0.5px solid rgba(45,212,191,0.3)",
            borderRadius: "10px 10px 2px 10px",
            padding: "7px 10px",
            fontSize: 11,
            color: "#e5e5e5",
            lineHeight: 1.5,
            whiteSpace: "pre-wrap",
            wordBreak: "break-word",
          }}
        >
          {entry.content}
        </div>
        <div
          style={{
            fontSize: 9,
            color: "#525252",
            marginTop: 3,
            textAlign: "right",
            paddingRight: 2,
          }}
        >
          {relativeTime(entry.timestamp)}
        </div>
      </div>
    </div>
  );
}

function ThinkingBubble() {
  return (
    <div style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
      <div style={{ flexShrink: 0, marginTop: 2 }}>
        <GhostMascot state="thinking" size={22} />
      </div>
      <div
        style={{
          background: "#1a1a1a",
          border: "0.5px solid rgba(255,255,255,0.06)",
          borderRadius: "2px 10px 10px 10px",
          padding: "10px 12px",
          display: "flex",
          gap: 3,
          alignItems: "center",
        }}
      >
        {[0, 1, 2].map((i) => (
          <div
            key={i}
            style={{
              width: 4,
              height: 4,
              borderRadius: "50%",
              background: "#2dd4bf",
              animation: `thinkDot 1.2s ease-in-out ${i * 0.15}s infinite`,
            }}
          />
        ))}
      </div>
    </div>
  );
}
