// src/renderer/screens/Settings.tsx
import React from 'react';
import type { AppSettings } from '../../shared/ipc-contract';

interface Props {
  settings: AppSettings;
  onBack: () => void;
  onChange: (patch: Partial<AppSettings>) => void;
}

// ─── Exported icon — imported by other screens ───────────────────────────────

export function GearIcon({ size = 13 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <path
        stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
        d="M9.594 3.94c.09-.542.56-.94 1.11-.94h2.593c.55 0 1.02.398 1.11.94l.213 1.281c.063.374.313.686.645.87.074.04.147.083.22.127.325.196.72.257 1.075.124l1.217-.456a1.125 1.125 0 0 1 1.37.49l1.296 2.247a1.125 1.125 0 0 1-.26 1.431l-1.003.827c-.293.241-.438.613-.43.992a7.723 7.723 0 0 1 0 .255c-.008.378.137.75.43.991l1.004.827c.424.35.534.955.26 1.43l-1.298 2.247a1.125 1.125 0 0 1-1.369.491l-1.217-.456c-.355-.133-.75-.072-1.076.124a6.47 6.47 0 0 1-.22.128c-.331.183-.581.495-.644.869l-.213 1.281c-.09.543-.56.94-1.11.94h-2.594c-.55 0-1.019-.398-1.11-.94l-.213-1.281c-.062-.374-.312-.686-.644-.87a6.52 6.52 0 0 1-.22-.127c-.325-.196-.72-.257-1.076-.124l-1.217.456a1.125 1.125 0 0 1-1.369-.49l-1.297-2.247a1.125 1.125 0 0 1 .26-1.431l1.004-.827c.292-.24.437-.613.43-.991a6.932 6.932 0 0 1 0-.255c.007-.38-.138-.751-.43-.992l-1.004-.827a1.125 1.125 0 0 1-.26-1.43l1.297-2.247a1.125 1.125 0 0 1 1.37-.491l1.216.456c.356.133.751.072 1.076-.124.072-.044.146-.086.22-.128.332-.183.582-.495.644-.869l.214-1.28Z"
      />
      <path
        stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
        d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"
      />
    </svg>
  );
}

// ─── Private helpers ─────────────────────────────────────────────────────────

function Toggle({ on, onChange, accent }: { on: boolean; onChange: (v: boolean) => void; accent: string }) {
  return (
    <button
      onClick={() => onChange(!on)}
      style={{
        width: 36, height: 20, borderRadius: 10,
        background: on ? accent : 'rgba(255,255,255,0.1)',
        border: 'none', cursor: 'pointer', position: 'relative',
        transition: 'background 0.2s', flexShrink: 0,
      }}
    >
      <div style={{
        position: 'absolute', top: 2, left: on ? 18 : 2,
        width: 16, height: 16, borderRadius: '50%',
        background: '#fff', transition: 'left 0.2s',
        boxShadow: '0 1px 2px rgba(0,0,0,0.4)',
      }} />
    </button>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div style={{
      fontSize: 9, color: '#737373', textTransform: 'uppercase',
      letterSpacing: '0.1em', marginBottom: 14, fontWeight: 500,
    }}>
      {children}
    </div>
  );
}

const ACCENT_COLORS: Record<AppSettings['accentColor'], string> = {
  teal:   '#2dd4bf',
  violet: '#a78bfa',
  amber:  '#facc15',
};

// ─── Component ───────────────────────────────────────────────────────────────

export default function Settings({ settings, onBack, onChange }: Props) {
  const accent = ACCENT_COLORS[settings.accentColor] ?? '#2dd4bf';
  const thresholdMin = Math.max(1, Math.round(settings.inactivityThreshold / 60));

  return (
    <div style={{
      position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
      display: 'flex', flexDirection: 'column',
      fontFamily: "'Inter', sans-serif", color: '#e5e5e5', overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        padding: '14px 16px 12px',
        borderBottom: '0.5px solid rgba(255,255,255,0.06)',
        display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0,
      }}>
        <button
          onClick={onBack}
          style={{ background: 'transparent', border: 'none', color: '#737373', fontSize: 14, cursor: 'pointer', padding: 0, lineHeight: 1, flexShrink: 0 }}
        >
          ←
        </button>
        <div>
          <div style={{ fontSize: 12, fontWeight: 500, color: '#e5e5e5', letterSpacing: '-0.01em' }}>settings</div>
          <div style={{ fontSize: 10, color: '#737373' }}>tune your ghost</div>
        </div>
      </div>

      {/* Scrollable body */}
      <div className="fg-scroll" style={{ flex: 1, overflowY: 'auto', padding: '16px 16px 24px' }}>

        {/* ── APPEARANCE ─────────────────────────────────────────────────────── */}
        <SectionLabel>appearance</SectionLabel>

        {/* Accent color */}
        <div style={{ marginBottom: 18 }}>
          <div style={{ fontSize: 12, color: '#e5e5e5', marginBottom: 8 }}>accent</div>
          <div style={{ display: 'flex', gap: 6 }}>
            {(['teal', 'violet', 'amber'] as const).map(c => {
              const col = ACCENT_COLORS[c];
              const sel = settings.accentColor === c;
              return (
                <button
                  key={c}
                  onClick={() => onChange({ accentColor: c })}
                  style={{
                    flex: 1, background: sel ? `${col}18` : '#1a1a1a',
                    border: `0.5px solid ${sel ? col : 'rgba(255,255,255,0.08)'}`,
                    borderRadius: 5, padding: '7px 0', fontSize: 11,
                    color: sel ? col : '#737373', fontFamily: 'inherit',
                    cursor: 'pointer', transition: 'all 0.15s',
                  }}
                >
                  {c}
                </button>
              );
            })}
          </div>
        </div>

        {/* Always on top */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <div>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>always on top</div>
            <div style={{ fontSize: 10, color: '#737373', marginTop: 2 }}>keep the window above other apps</div>
          </div>
          <Toggle on={settings.alwaysOnTop} onChange={v => onChange({ alwaysOnTop: v })} accent={accent} />
        </div>

        {/* Auto-collapse */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
          <div>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>auto-collapse when idle</div>
            <div style={{ fontSize: 10, color: '#737373', marginTop: 2 }}>shrink to bar after 30s of inactivity</div>
          </div>
          <Toggle on={settings.autoCollapse} onChange={v => onChange({ autoCollapse: v })} accent={accent} />
        </div>

        {/* Auto-dim */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
          <div>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>auto-dim when idle</div>
            <div style={{ fontSize: 10, color: '#737373', marginTop: 2 }}>fade window after 5s so you can see through it</div>
          </div>
          <Toggle on={settings.autoDim} onChange={v => onChange({ autoDim: v })} accent={accent} />
        </div>

        {/* Divider */}
        <div style={{ height: '0.5px', background: 'rgba(255,255,255,0.06)', marginBottom: 18 }} />

        {/* ── NUDGES ─────────────────────────────────────────────────────────── */}
        <SectionLabel>nudges</SectionLabel>

        {/* Sensitivity */}
        <div style={{ marginBottom: 18 }}>
          <div style={{ fontSize: 12, color: '#e5e5e5', marginBottom: 3 }}>sensitivity</div>
          <div style={{ fontSize: 10, color: '#737373', marginBottom: 8 }}>how quickly the ghost speaks up when you drift</div>
          <div style={{ display: 'flex', gap: 6 }}>
            {(['gentle', 'balanced', 'strict'] as const).map(s => {
              const sel = settings.nudgeSensitivity === s;
              return (
                <button
                  key={s}
                  onClick={() => onChange({ nudgeSensitivity: s })}
                  style={{
                    flex: 1, background: sel ? 'rgba(255,255,255,0.06)' : '#1a1a1a',
                    border: `0.5px solid ${sel ? 'rgba(255,255,255,0.25)' : 'rgba(255,255,255,0.08)'}`,
                    borderRadius: 5, padding: '7px 0', fontSize: 11,
                    color: sel ? accent : '#737373', fontFamily: 'inherit',
                    cursor: 'pointer', transition: 'all 0.15s',
                  }}
                >
                  {s}
                </button>
              );
            })}
          </div>
        </div>

        {/* Drift threshold */}
        <div style={{ marginBottom: 18 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>drift threshold</div>
            <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: accent, fontVariantNumeric: 'tabular-nums' }}>
              {thresholdMin} min
            </div>
          </div>
          <input
            type="range" min={1} max={10} value={thresholdMin}
            onChange={e => onChange({ inactivityThreshold: Number(e.target.value) * 60 })}
            style={{ width: '100%', accentColor: accent, cursor: 'pointer' }}
          />
        </div>

        {/* Proactive insights */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>proactive insights</div>
            <div style={{ fontSize: 10, color: '#737373', marginTop: 2 }}>ghost shares patterns it notices mid-session</div>
          </div>
          <Toggle on={settings.nudgeEnabled} onChange={v => onChange({ nudgeEnabled: v })} accent={accent} />
        </div>
        
        {/* Voice Enabled */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontSize: 12, color: '#e5e5e5' }}>voice enabled</div>
            <div style={{ fontSize: 10, color: '#737373', marginTop: 2 }}>ghost speaks up when you drift</div>
          </div>
          <Toggle on={settings.voiceEnabled} onChange={v => onChange({ voiceEnabled: v })} accent={accent} />
        </div>
      </div>
    </div>
  );
}

// src/renderer/screens/Settings.svelte
<script lang="ts">
  import { settings } from '../stores/app';
  import { updateSettings } from '../lib/electron';
  import type { AppSettings } from '../../shared/ipc-contract';
  import { DEFAULT_SETTINGS } from '../../shared/ipc-contract';

  interface Props {
    onBack: () => void;
  }

  let { onBack }: Props = $props();

  let currentSettings = $state<AppSettings>({ ...DEFAULT_SETTINGS });

  settings.subscribe(s => {
    currentSettings = { ...s };
  });

  function handleOpacityChange(value: number) {
    currentSettings.opacity = value;
    updateSettings({ opacity: value });
  }

  function handleAccentColor(color: 'teal' | 'violet' | 'amber') {
    currentSettings.accentColor = color;
    updateSettings({ accentColor: color });
  }

  function handleNudgeSensitivity(sensitivity: 'gentle' | 'balanced' | 'strict') {
    currentSettings.nudgeSensitivity = sensitivity;
    updateSettings({ nudgeSensitivity: sensitivity });
  }

  function handleToggle(key: 'alwaysOnTop' | 'autoCollapse' | 'nudgeEnabled', value: boolean) {
    currentSettings[key] = value;
    updateSettings({ [key]: value });
  }

  function handleDriftThreshold(value: number) {
    currentSettings.driftThreshold = value;
    updateSettings({ driftThreshold: value });
  }
</script>

<div class="settings-container">
  <div class="settings-header">
    <button class="back-btn" onclick={onBack} aria-label="back">
      ←
    </button>
    <div class="header-title">settings</div>
  </div>

  <div class="settings-body fg-scroll">
    <!-- APPEARANCE SECTION -->
    <div class="settings-section">
      <div class="section-title">appearance</div>

      <div class="setting-row">
        <div class="setting-label">opacity</div>
        <div class="setting-control">
          <input
            type="range"
            min="0.5"
            max="1"
            step="0.1"
            value={currentSettings.opacity}
            onchange={(e) => handleOpacityChange(parseFloat(e.currentTarget.value))}
            class="slider"
          />
          <span class="value-display">{Math.round(currentSettings.opacity * 100)}%</span>
        </div>
      </div>

      <div class="setting-row">
        <div class="setting-label">accent color</div>
        <div class="setting-control">
          <div class="color-picker">
            <button
              class="color-btn"
              class:active={currentSettings.accentColor === 'teal'}
              onclick={() => handleAccentColor('teal')}
              style="background: #2dd4bf"
              title="teal"
            />
            <button
              class="color-btn"
              class:active={currentSettings.accentColor === 'violet'}
              onclick={() => handleAccentColor('violet')}
              style="background: #a78bfa"
              title="violet"
            />
            <button
              class="color-btn"
              class:active={currentSettings.accentColor === 'amber'}
              onclick={() => handleAccentColor('amber')}
              style="background: #fbbf24"
              title="amber"
            />
          </div>
        </div>
      </div>

      <div class="setting-row">
        <div class="setting-label">always on top</div>
        <div class="setting-control">
          <input
            type="checkbox"
            checked={currentSettings.alwaysOnTop}
            onchange={(e) => handleToggle('alwaysOnTop', e.currentTarget.checked)}
            class="toggle"
          />
        </div>
      </div>

      <div class="setting-row">
        <div class="setting-label">auto-collapse</div>
        <div class="setting-control">
          <input
            type="checkbox"
            checked={currentSettings.autoCollapse}
            onchange={(e) => handleToggle('autoCollapse', e.currentTarget.checked)}
            class="toggle"
          />
        </div>
      </div>
    </div>

    <!-- NUDGES SECTION -->
    <div class="settings-section">
      <div class="section-title">nudges</div>

      <div class="setting-row">
        <div class="setting-label">sensitivity</div>
        <div class="setting-control">
          <select
            value={currentSettings.nudgeSensitivity}
            onchange={(e) => handleNudgeSensitivity(e.currentTarget.value as 'gentle' | 'balanced' | 'strict')}
            class="dropdown"
          >
            <option value="gentle">gentle</option>
            <option value="balanced">balanced</option>
            <option value="strict">strict</option>
          </select>
        </div>
      </div>

      <div class="setting-row">
        <div class="setting-label">drift threshold</div>
        <div class="setting-control">
          <input
            type="range"
            min="2"
            max="10"
            step="1"
            value={currentSettings.driftThreshold}
            onchange={(e) => handleDriftThreshold(parseInt(e.currentTarget.value))}
            class="slider"
          />
          <span class="value-display">{currentSettings.driftThreshold}min</span>
        </div>
      </div>

      <div class="setting-row">
        <div class="setting-label">nudges enabled</div>
        <div class="setting-control">
          <input
            type="checkbox"
            checked={currentSettings.nudgeEnabled}
            onchange={(e) => handleToggle('nudgeEnabled', e.currentTarget.checked)}
            class="toggle"
          />
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  .settings-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    font-family: 'Inter', sans-serif;
    color: #e5e5e5;
    overflow: hidden;
    background: #111111;
  }

  .settings-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 14px;
    border-bottom: 0.5px solid rgba(255, 255, 255, 0.06);
  }

  .back-btn {
    background: transparent;
    border: none;
    color: #737373;
    font-size: 14px;
    cursor: pointer;
    padding: 0;
    line-height: 1;
    flex-shrink: 0;
  }

  .header-title {
    font-size: 12px;
    font-weight: 500;
    color: #e5e5e5;
    letter-spacing: -0.01em;
  }

  .settings-body {
    flex: 1;
    overflow-y: auto;
    padding: 14px 12px;
    display: flex;
    flex-direction: column;
    gap: 20px;
  }

  .settings-section {
    display: flex;
    flex-direction: column;
    gap: 12px;
  }

  .section-title {
    font-size: 10px;
    font-weight: 600;
    color: #737373;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    margin-bottom: 4px;
  }

  .setting-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 12px;
    padding: 8px 10px;
    background: rgba(255, 255, 255, 0.02);
    border-radius: 6px;
    border: 0.5px solid rgba(255, 255, 255, 0.04);
  }

  .setting-label {
    font-size: 11px;
    color: #a3a3a3;
    flex: 1;
  }

  .setting-control {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-shrink: 0;
  }

  .slider {
    width: 70px;
    height: 4px;
    border-radius: 2px;
    background: rgba(45, 212, 191, 0.2);
    outline: none;
    -webkit-appearance: none;
    appearance: none;
  }

  .slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: #2dd4bf;
    cursor: pointer;
  }

  .slider::-moz-range-thumb {
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: #2dd4bf;
    cursor: pointer;
    border: none;
  }

  .value-display {
    font-size: 10px;
    color: #737373;
    font-family: 'JetBrains Mono', monospace;
    min-width: 32px;
    text-align: right;
  }

  .color-picker {
    display: flex;
    gap: 6px;
  }

  .color-btn {
    width: 20px;
    height: 20px;
    border-radius: 4px;
    border: 2px solid transparent;
    cursor: pointer;
    transition: all 0.15s;
  }

  .color-btn.active {
    border-color: #2dd4bf;
    box-shadow: 0 0 8px rgba(45, 212, 191, 0.3);
  }

  .toggle {
    width: 32px;
    height: 18px;
    border-radius: 9px;
    border: none;
    background: rgba(255, 255, 255, 0.1);
    cursor: pointer;
    position: relative;
    appearance: none;
    -webkit-appearance: none;
  }

  .toggle:checked {
    background: #2dd4bf;
  }

  .dropdown {
    background: #1a1a1a;
    border: 0.5px solid rgba(255, 255, 255, 0.08);
    border-radius: 4px;
    color: #e5e5e5;
    font-size: 10px;
    padding: 4px 6px;
    cursor: pointer;
    font-family: inherit;
  }

  .dropdown:hover {
    border-color: rgba(255, 255, 255, 0.15);
  }
</style>
